[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002266A979E50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/be6e90e259202df2ff0673da72bf1236
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002266CF64990>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/be6e90e259202df2ff0673da72bf1236
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002266AD85490>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/be6e90e259202df2ff0673da72bf1236